const LINKS={"free-question":"https://example.com/private-reading","telegram":"https://t.me/your-community","facebook":"https://facebook.com/your-group","booking":"https://example.com/booking","payment":"https://example.com/payment","email":"mailto:hello@example.com"};
document.querySelectorAll('[data-link]').forEach(el=>{const key=el.dataset.link;if(LINKS[key])el.href=LINKS[key]});
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const menuButton=document.querySelector('.menu-button'),mobileMenu=document.querySelector('.mobile-menu');
function setMenu(open){mobileMenu?.classList.toggle('open',open);menuButton?.setAttribute('aria-expanded',String(open));mobileMenu?.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''}
menuButton?.addEventListener('click',()=>setMenu(!mobileMenu.classList.contains('open')));document.querySelectorAll('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const tabs=document.querySelectorAll('.console-tab');const system=document.getElementById('consoleSystem'),title=document.getElementById('consoleTitle'),subtitle=document.getElementById('consoleSubtitle'),text=document.getElementById('consoleText');
const consoleData={ziwei:['ZI WEI DOU SHU / ZI WEI DOU SHU','12 PALACES','LIFE AREAS · RELATIONSHIPS · TIMING','A chart is read through relationships between symbols, life domains and timing — not through one isolated sign.'],wuxing:['FIVE ELEMENTS / WU XING','FIVE MOVEMENTS','GENERATION · RESTRAINT · TRANSFORMATION','The Five Elements describe dynamic modes of movement and the relationships between them.'],bagua:['BAGUA / DIRECTIONS','SPACE & DIRECTION','ORIENTATION · ENVIRONMENT · RELATIONSHIPS','Bagua provides a symbolic language for orientation, space and changing conditions.'],timing:['TIMING / CYCLES','CHANGING FIELD','CYCLES · TRANSITIONS · MOMENTS','Timing is approached as a way to observe changing conditions, not as a guarantee of outcomes.']};
tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');const d=consoleData[t.dataset.system]||consoleData.ziwei;[system.textContent,title.textContent,subtitle.textContent,text.textContent]=d;}));
const birthDate=document.getElementById('birthDate'),birthTime=document.getElementById('birthTime'),birthPlace=document.getElementById('birthPlace'),visualizeBtn=document.getElementById('visualizeBtn'),fieldCode=document.getElementById('fieldCode');
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++)h=Math.imul(h^str.charCodeAt(i),16777619);return h>>>0}
visualizeBtn?.addEventListener('click',()=>{const raw=`${birthDate?.value||''}|${birthTime?.value||''}|${birthPlace?.value||''}`;const n=hash(raw);const deg=n%360;if(fieldCode)fieldCode.textContent=`FIELD ${String(deg).padStart(3,'0')}°`;visualizeBtn.textContent='Visualized ✓'});
const palaceNames=[['Self','SELF / IDENTITY'],['Siblings','SIBLINGS / PEERS'],['Relationship','RELATIONSHIP'],['Creation','CREATION / EXPRESSION'],['Resources','RESOURCES / WEALTH'],['Wellbeing','WELLBEING'],['Movement','MOVEMENT / TRAVEL'],['Community','COMMUNITY / NETWORK'],['Career','CAREER / WORK'],['Home','HOME / PROPERTY'],['Inner Life','INNER LIFE'],['Origins','ORIGINS / ROOTS']];
const stars=['Zi Wei','Tian Fu','Tian Ji','Tai Yang','Wu Qu','Tian Tong','Lian Zhen','Tian Xiang','Qi Sha','Po Jun','Tai Yin','Tan Lang'];const elements=['Earth','Wood','Water','Fire','Metal'];const descriptions=['The symbolic center of the chart — traditionally associated with how a person approaches the world and experiences themselves.','A field for considering peer relationships, exchange and social comparison.','A symbolic space for examining connection, attraction and recurring relationship dynamics.','A field associated with expression, creativity and what one brings into the world.','A symbolic lens for resources, value, support and material conditions.','A field for considering vitality, habits and the conditions that support wellbeing.','A space associated with movement, travel, change of environment and expansion.','A lens for networks, community, collaboration and collective context.','A field for work, responsibility, ambition and professional direction.','A symbolic space for home, foundations, belonging and place.','A field for reflection, inner patterns, retreat and personal meaning.','A lens for origins, family context and the conditions that shape early life.'];
const ring=document.getElementById('palaceRing');const starTrack=document.getElementById('starTrack');let selected=0;
function renderLab(){if(!ring||!starTrack)return;ring.innerHTML='';starTrack.innerHTML='';palaceNames.forEach((p,i)=>{const angle=(-90+i*30)*Math.PI/180;const x=50+42*Math.cos(angle),y=50+42*Math.sin(angle);const node=document.createElement('button');node.type='button';node.className='palace-node'+(i===selected?' active':'');node.style.left=x+'%';node.style.top=y+'%';node.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><small>${p[0]}</small>`;node.addEventListener('click',()=>{selected=i;renderLab();updatePanel()});ring.appendChild(node);const sx=50+31*Math.cos(angle),sy=50+31*Math.sin(angle);const s=document.createElement('i');s.className='lab-star';s.style.left=sx+'%';s.style.top=sy+'%';starTrack.appendChild(s)});updatePanel()}
function updatePanel(){const p=palaceNames[selected];const n=document.getElementById('palaceIndex'),name=document.getElementById('palaceName'),eng=document.getElementById('palaceEnglish'),desc=document.getElementById('palaceDescription'),star=document.getElementById('primaryStar'),el=document.getElementById('palaceElement'),pos=document.getElementById('palacePosition');if(n)n.textContent=String(selected+1).padStart(2,'0');if(name)name.textContent=p[0];if(eng)eng.textContent=p[1];if(desc)desc.textContent=descriptions[selected];if(star)star.textContent=stars[selected];if(el)el.textContent=elements[selected%elements.length];if(pos)pos.textContent=selected===0?'CENTER FIELD':`${selected*30}° / ORBIT FIELD`}
renderLab();
